# Generated by Django 5.2 on 2025-04-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0005_alter_borrowing_actual_return_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="actual_return_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
