# Generated by Django 5.2 on 2025-04-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings_service", "0004_borrowing_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="actual_return_date",
            field=models.DateField(default=None, null=True),
        ),
    ]
